CrudActMostajo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('gilead','App\Http\Controllers\GileadController');

CrudActMostajo/app/Models/Gilead.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gilead extends Model
{
    use HasFactory;

    protected $fillable=[

        'name','role','sex',
        ];
}

CrudActMostajo/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

CrudActMostajo/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

CrudActMostajo/app/Http/Controllers/GileadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gilead;
use Illuminate\Http\Request;

class GileadController extends Controller
{
    public function index()
    {
        $gilead=Gilead::latest()->paginate(5);
        return view ('gilead.index',compact('gilead'))
        ->with('i',(request()->input('page',1)-1)*5);
    
    }
    
    public function create()
    {
        return view('gilead.create');
    }
    
    
    public function store(Request $request)
    {
        $request->validate([
        'name'=>'required',
        'role'=>'required',
        'sex'=>'required',
    
    ]);
        Gilead::create($request->all());
    
        return redirect()->route('gilead.index')
        ->with('success', 'Citizen Added.');
    }
    
    
    
    public function edit(Gilead $gilead)
    {
    
        return view('gilead.edit',compact('gilead'));
    }
    
        public function update(Request $request,Gilead $gilead)
    {
        $request->validate([
    
    ]);
    
        $gilead->update($request->all());
    
        return redirect()->route('gilead.index')
        ->with('success','Person updated successfully');
    
    }
    
        public function destroy(Gilead $gilead)
    {
        $gilead->delete();
    
        return redirect()->route('gilead.index')
        ->with('success','Person deleted successfully');
    
    }
}

CrudActMostajo/resources/views/gilead/create.blade.php
@extends('gilead.layout')

@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Citizen</h2>
        </div>
    </div>
</div>

@if($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

    <form action="{{ route('gilead.store') }}" method="POST">
    
@csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Full Name">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Role</strong>
                    <input type="text" name="role" class="form-control" placeholder="Role">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Sex</strong>
                    <input type="text" name="sex" class="form-control" placeholder="Sex">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
				<a class="btn btn-primary" href="{{ route('gilead.index')}}">Back</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
@endsection

CrudActMostajo/resources/views/gilead/edit.blade.php
@extends('gilead.layout')

@section('content')

<div class="row">
	
	<div class="col-lg-12 margin-tb">
	<div class="pull-left">
	<br>
	<h2 style="text-align:center;">Edit Person Details</h2>
	<br>

</div>

	</div>
	</div>

@if ($errors->any())
	<div class="alert alert-danger">
	<strong>There were some problems with your input. <br><br>

	<ul>

	@foreach ($errors->all() as $error)

	<li>{{ $error }}</li>

	@endforeach
</ul>
</div>
@endif

<form action="{{ route('gilead.update',$gilead->id) }}" method="POST">
@csrf

 @method('PUT')
	<div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12">
	<div class="form-group">

	<strong>Name: </strong>

	<input type="text" name="name" value="{{ $gilead->name }}"

	class="form-control" placeholder="Name">

</div>
</div>

<div class="col-xs-12 col-sm-12 col-md-12">

	<div class="form-group">
	<strong>Role: </strong>

	<input type="text" name="role" value="{{ $gilead->role }}"
class="form-control" placeholder="Role">


</div>
</div>

<div class="col=xs=12 col-sm-12 col-md-12">
	
	<div class="form-group">
	<strong>Sex: </strong>
	<input type="text" name="sex" value="{{ $gilead->sex }}" class="form-control" placeholder="Sex">
</div>

<br>
<div style="text-align:center;">
	<a class="btn btn-primary" href="{{ route('gilead.index') }}">Back</a>

	<button type="submit" class="btn btn-primary">Submit</button>
</div>

</div>

</form>

@endsection

CrudActMostajo/resources/views/gilead/index.blade.php
@extends('gilead.layout')

@section('content')

<div class="pull-left">

	<br>
	<h2 style="text-align:center;">Gilead Citizens</h2>
	<br>


	</div>

	<div class="row">

	<div class="col-lg-12 margin-tb">
	</div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
<p>{{ $message }}</p>

</div>
@endif

<table class="table table-bordered">



<tr>

	<th>No</th>
	<th>Name</th>
	<th>Role</th>
	<th>Sex</th>
	<th width="280px">Action</th>
</tr>

@foreach ($gilead as $gilead)
<tr>

	<td>{{ ++$i }}</td>
	<td>{{ $gilead->name }}</td>
	<td>{{ $gilead->role }}</td>
	<td>{{ $gilead->sex }}</td>

	<td>
	<form action="{{ route('gilead.destroy',$gilead->id) }}" method="POST">
	

	<a class="btn btn-primary" href="{{ route('gilead.edit',$gilead->id) }}">Edit</a>

	@csrf
	@method('DELETE')

	<button type="submit" class="btn btn-danger">Delete</button>

	</form>

    </td>
</tr>
@endforeach
</table>

<br> 

<div style="text-align:center;">
	<a class="btn btn-success" href="{{ route('gilead.create') }}"> Add New Citizen</a>
</div>

CrudActMostajo/resources/views/gilead/layout.blade.php
<!DOCTYPE html>

<html>
<head>

<title>Gilead Citizens</title>

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
rel="stylesheet">

</head>
<body>

<div class="container">
@yield('content')
</div>

</body>
</html>